### ISSUE TITLE
JavaScript error in Edge

### ISSUE THREAD

**Issue by wietze** [mitre/attack-navigator#44] opened 2018-05-23 10:57 UTC
I can't get the Navigator v2 to work in Microsoft Edge. It works like a charm in Chrome, but in Edge I'm getting the following error when trying to open https://mitre.github.io/attack-navigator/enterprise/:

```
SCRIPT1005: Expected '('
main.5f1dd1c9fee06079d0b5.bundle.js (1,173241)
```
![image](https://user-images.githubusercontent.com/2811785/40420287-d9bd0f00-5e7f-11e8-996e-aacef2a322af.png)
I'm getting the same error when using my local version. The readme page says Edge is supported, is this a bug or did you drop support for Edge?

**Comment by jburns12** [comment] 2018-05-23 11:06
Hi @wietze ...thanks for bringing this up. One of our developers will check this out ASAP so we can implement a patch.

**Comment by jburns12** [comment] 2018-05-23 20:29
Hey @wietze - we were able to track down where the problem is in our codebase. We've updated our hosted instance on GitHub Pages to remove this error, but we're continuing to work on patching the code in our repo. Therefore local instances will still generate this error for the moment.

I'm going to leave this issue open until that work is resolved.

You may need to clear your cache/browsing history, but if you continue to have issues accessing https://mitre.github.io/attack-navigator on Edge or otherwise, please let us know. Thanks again!

**Comment by wietze** [comment] 2018-05-24 12:06
I can confirm your GitHub Pages instance works again under Edge. Thanks for looking into this.

**Comment by thatfiferguy** [comment] 2018-05-24 13:50
The error came from the taxii2lib library which was not getting polyfilled for IE & Edge compatability. To fix the bug we converted taxii2lib.js to typescript so that webpack could polyfill it for IE & Edge compatability.

The fix was implemented in [fix/taxii2lib-polyfills](https://github.com/mitre/attack-navigator/tree/fix/taxii2lib-polyfills) and merged into master.

**Closed by thatfiferguy** 2018-05-24 13:50 UTC
