### ISSUE TITLE
Long comments 

### ISSUE THREAD

**Issue by phlogis** [mitre/attack-navigator#23] opened 2018-03-19 18:33 UTC
Putting a long comment on a technique at the bottom will cut off so you cannot see the rest of the comment.  When you scroll it then flashes.  This occurs in the latest Chrome.  
![untitled](https://user-images.githubusercontent.com/22580538/37614979-6d71beb4-2bac-11e8-85ed-16ab58c3e128.png)

**Comment by jburns12** [comment] 2018-03-19 18:53
Thanks for pointing this out, @phlogis . We'll take a look at this and keep this issue updated based on our progress.

**Comment by thatfiferguy** [comment] 2018-03-21 12:08
A fix for tooltip length was implemented in the branch [bugs/long-tooltips](https://github.com/mitre/attack-navigator/tree/bugs/long-tooltips) and merged into develop. Two changes to the behavior of tooltips were implemented to mitigate the issue.

1. The comment section of the tooltip now has a height limit of 300px. This is long enough to show a lot of information while protecting from display issues caused by extremely long comments. The presence of overflowed text is denoted by ellipses (...). Here's a screenshot of how the comment box now looks with a long comment: 

    <img width="185" alt="screen shot 2018-03-21 at 7 46 42 am" src="https://user-images.githubusercontent.com/28868888/37708757-3a39fcae-2cde-11e8-9db0-ea3540268a37.png">

    Longer comments can still be seen by opening the comment edit field in the technique controls menu.

2. The tooltip now flips to anchor above the mouse cursor when near the bottom of the page so that it doesn't overflow off the bottom of the page and cause the scrolling behavior you experienced.

**Closed by thatfiferguy** 2018-03-21 12:08 UTC
Labels: bug
